# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 8.x
    performMultiLevelLookup: true
    
- checkout: self
  displayName: 'Checkout'

- task: DotNetCoreCLI@2
  displayName: 'Display project dependencies'
  inputs:
    command: restore

- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  inputs:
    command: test
    projects: '**/*.UnitTests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code Coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Build & Deploy artifact'
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--no-restore --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishPipelineArtifact@1
  displayName: 'Publishing WebApp artifact'
  condition: succeeded()
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'webapp'