# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  BUILD_CONFIGURATION: 'Release'
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 8.x
    performMultiLevelLookup: true
    
- checkout: self
  displayName: 'Checkout'

- task: DotNetCoreCLI@2
  displayName: 'Check Format'
  inputs:
    command: 'custom'
    custom: 'format'
    arguments: '--verify-no-changes'

- task: Cache@2
  displayName: 'NuGet Caching'
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
    restoreKeys: |
      nuget | "$(Agent.OS)"
      nuget
    path: '$(BUILD_CONFIGURATION)'
    cacheHitVar: 'CACHE_RESTORED'

- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  condition: ne(variables.CACHE_RESTORED, true)
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  inputs:
    command: test
    projects: '**/*.UnitTests/*.csproj'
    arguments: '--configuration $(BUILD_CONFIGURATION) --collect "Code Coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Build & Deploy artifact'
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--no-restore --configuration $(BUILD_CONFIGURATION) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishPipelineArtifact@1
  displayName: 'Publishing WebApp artifact'
  condition: succeeded()
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'webapp'