parameters:
  BUILD_CONFIGURATION: 'Release'
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

steps:
- task: Cache@2
  displayName: 'NuGet Caching'
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
    restoreKeys: |
      nuget | "$(Agent.OS)"
      nuget
    path: '$(NUGET_PACKAGES)'
    cacheHitVar: 'CACHE_RESTORED'

- script: dotnet clean --configuration $(BUILD_CONFIGURATION)
  displayName: 'Clean previous build output'

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Restore'
  condition: ne(variables.CACHE_RESTORED, true)
  inputs:
    command: restore
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  inputs:
    command: test
    publishTestResults: true
    testRunTitle: 'Unit Tests'
    projects: '**/*.UnitTests/*.csproj'
    arguments: >
      --configuration $(BUILD_CONFIGURATION)
      /p:CollectCoverage=true 
      /p:CoverletOutputFormat=cobertura 
      /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/

- task: DotNetCoreCLI@2
  displayName: 'CodeCoverage Report'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'reportgenerator -reports:$(Build.SourcesDirectory)/TestResults/Coverage/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/TestResults/Coverage/Report -reporttypes:HtmlInline_AzurePipelines'

- task: DotNetCoreCLI@2
  displayName: 'Build & Deploy artifact'
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--no-restore --configuration $(BUILD_CONFIGURATION) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true