parameters:
  - name: vmImage
    type: string

  - name: artifactName
    type: string
    
  - name: environment
    type: string

  - name: buildConfiguration
    type: string
    default: 'Release'
    
  - name: webAppName
    type: string

jobs:
  - deployment: DeployWebApp
    displayName: 'Deploy Web App'
    pool:
      vmImage: ${{ parameters.vmImage }}
    environment: ${{ parameters.environment }}
    variables:
    - group: 'Release'
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: ${{ parameters.artifactName }}
            - task: AzureWebApp@1
              displayName: 'Deploy to Azure Web App'
              inputs:
                  azureSubscription: 'cstadimod-arm-sc'
                  appName: ${{ parameters.webAppName }}
                  appType: 'webApp'
                  package: '$(Pipeline.Workspace)/WebAppArtifact/${{ parameters.buildConfiguration }}/*.zip' #TODO: better to change ** to specific name